database:
  url: "mysql+aiomysql://root:Aa123456@localhost:3306/rbac_system"
  pool_size: 10
  max_overflow: 10
  pool_timeout: 30
  pool_pre_ping: true

security:
  secret_key: "your-secret-key"
  algorithm: "HS256"
  access_token_expire_minutes: 720

logging:
  level: "INFO"
  file: "logs/app.log"